import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Chocolate Lava Cake',
    description: 'Indulgent individual chocolate cake with a molten fudge center. Best served warm.',
    price: 8.5,
    imageId: 'chocolate-lava-cake',
    category: 'Cakes',
    dietary: ['Nut-Free'],
  },
  {
    id: 'prod_002',
    name: 'Red Velvet Delight',
    description: 'A southern classic. Velvety red cake with our signature cream cheese frosting.',
    price: 7.0,
    imageId: 'red-velvet-delight',
    category: 'Cakes',
    dietary: [],
  },
  {
    id: 'prod_003',
    name: 'Fudgy Vegan Brownies',
    description: 'Rich, dark, and decadent vegan brownies that you would never guess are plant-based.',
    price: 5.5,
    imageId: 'fudgy-vegan-brownies',
    category: 'Brownies',
    dietary: ['Vegan'],
  },
  {
    id: 'prod_004',
    name: 'Classic Chocolate Chip Cookies',
    description: 'Perfectly soft and chewy, loaded with semi-sweet chocolate chips. Sold by the half-dozen.',
    price: 15.0,
    imageId: 'classic-chocolate-chip-cookies',
    category: 'Cookies',
    dietary: [],
  },
  {
    id: 'prod_005',
    name: 'Gluten-Free Oatmeal Cookies',
    description: 'A wholesome and delicious treat made with certified gluten-free oats and raisins.',
    price: 16.5,
    imageId: 'gluten-free-oatmeal-cookies',
    category: 'Cookies',
    dietary: ['Gluten-Free'],
  },
  {
    id: 'prod_006',
    name: 'Nutty Walnut Brownies',
    description: 'Our classic fudgy brownie packed with toasted walnuts for a satisfying crunch.',
    price: 6.0,
    imageId: 'nutty-walnut-brownies',
    category: 'Brownies',
    dietary: [],
  },
  {
    id: 'prod_007',
    name: 'Strawberry Shortcake',
    description: 'Light and airy sponge cake layered with fresh strawberries and whipped cream.',
    price: 45.0,
    imageId: 'strawberry-shortcake',
    category: 'Cakes',
    dietary: ['Nut-Free'],
  },
  {
    id: 'prod_008',
    name: 'Vegan & GF Blueberry Muffins',
    description: 'Moist, fluffy, and bursting with blueberries. A perfect guilt-free indulgence.',
    price: 4.5,
    imageId: 'blueberry-muffins',
    category: 'Cookies', // Categorized as cookies to show variety
    dietary: ['Vegan', 'Gluten-Free'],
  },
];
